# Generated by Django 5.1.5 on 2025-02-09 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecep_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecep_api.etablissement'),
        ),
    ]
