# Generated by Django 5.1.5 on 2025-02-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecep_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
