# Generated by Django 5.1.5 on 2025-02-09 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecep_api', '0002_user_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='ecep_api.etablissement'),
        ),
    ]
