# Generated by Django 5.1.5 on 2025-02-09 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecep_api', '0003_alter_course_etablissement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='contenu',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fichier_pdf',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video_url',
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('numero', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='ecep_api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='lecons_pdfs/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('numero', models.PositiveIntegerField()),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='ecep_api.chapitre')),
            ],
        ),
    ]
