# Generated by Django 5.1.5 on 2025-02-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecep_api', '0005_remove_exercise_type_exercise_correction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='exercises/pdf/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('quiz', 'Quiz temporisé'), ('pdf', 'Exercice PDF'), ('qcm', 'QCM simple')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
